# Raising an exception :
l =  [1,2,3,4]
sum  =0
for i in l:
    if i==1:
        raise Exception ("Excption : 1 is found")
    else:
        sum +=1
# Exception: Excption : 1 is found

